### ISSUE TITLE
Absence de documentation pour démarrer

### ISSUE THREAD

**Issue by mbideau** [jzck/Open3CL#78]
Bonjour,

Bravo pour cette initiative logicielle qui pourrait être un service public !

J'ai voulu voir à quel point mon DPE était "reconnu" par Open3CL, mais après avoir lancé la suite de test via `npm run test` j'ai de très nombreux FAIL. Je me demande donc si j'ai mal fait quelque chose au niveau de l'installation et/ou de la configuration de l'environnement de dev... Sans doc, difficile d'évaluer ça moi-même.

Voilà les commandes effectuées:
```sh
$ lsb_release -ds
Debian GNU/Linux 11 (bullseye)
$ node --version
v22.8.0

$ git clone git@github.com:jzck/Open3CL.git
$ cd Open3CL
$ npm install
$ npm run test
```

Et voilà le résultat:
```
...tronqué...
Test Suites: 19 failed, 6 passed, 25 total
Tests:       17917 failed, 1428 skipped, 22298 passed, 41643 total
Snapshots:   0 total
Time:        449.337 s
Ran all test suites.
```

J'ai également tenté:
```sh
npm run assets:sync

> @jzck/open3cl@0.1.0 assets:sync
> node scripts/synchronize_assets.js

Could not synchronize files Error: Invalid HTML: could not find <table>
    at html_to_workbook (/om/apps/open3CL/node_modules/xlsx/xlsx.js:20888:38)
    at parse_xlml_xml (/om/apps/open3CL/node_modules/xlsx/xlsx.js:17291:20)
    at parse_xlml (/om/apps/open3CL/node_modules/xlsx/xlsx.js:18033:24)
    at readSync (/om/apps/open3CL/node_modules/xlsx/xlsx.js:23709:21)
    at Module.readSync (/om/apps/open3CL/node_modules/xlsx/xlsx.js:23691:79)
    at file:///om/apps/open3CL/src/core/file/infrastructure/adapter/file.store.js:16:40
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 0)
    at async file:///om/apps/open3CL/scripts/synchronize_assets.js:22:1
```

Je suggère d'ajouter une petite section dans le README pour indiquer comment démarrer.
Et je serais aussi preneur d'indications pour savoir comment tester le logiciel sur un seul DPE (dont on a le numéro), pour voir le pourcentage de correspondance à l'original et quel sont les éléments qui diffèrent.

Merci encore et bon courage.

**Comment by mbideau** [comment]
En fouillant dans le code, j'ai trouvé le script `test/test.sh` qui répond à mes attentes et m'a permis de produire un DPE avec Open3CL et de le comparer à l'original.
Comme documenté en entête de ce fichier, il faut lancer les commandes suivantes :
```
$ test.sh _download_one <DPE>
$ test.sh _run_one <DPE>
$ test.sh _diff_one <DPE>
```

Afin de faire fonctionner ce script (et ses dépendances) j'ai dû faire 2 commandes supplémentaires (cf #79 et #80) :
```
$ sudo ln -s /usr/bin/node /usr/local/bin/bun
$ npm install json-diff
```

Astuce: pour un confort de lecture je redirige la sortie de la dernière commande dans `| less -R`.

Maintenant que j'ai un résultat, je ne sais pas comment analyser les différences avec l'original, dans le sens de comprendre pourquoi telle différence est présente, et son importance dans le calcul global.

En tous cas bravo car, dans mon cas, la classe DPE est reconnue de manière identique pour le coût et les GES :+1: 

Encore merci pour ce boulo super.

**Comment by jzck** [comment]
Salut! merci pour tes commentaires, je sais bien qu'il n'y a pas de doc démarrage, je n'ai pas voulu documenter `test.sh` parceque c'est un peu un hack que j'avais fait pour tester mon code, j'aimerai bien faire un cli `open3cl` qui reprends les fonctionalité de `test.sh` et qui serait installable facilement avec npm...
Mais: 
1. c'est un peu prématuré car il y a encore plein de soucis dans le moteur de calcul, je n'ai pas envie d'inciter les gens a utiliser open3cl sur leur dpe tout de suite car les résultats sont souvent faux
2. je n'ai pas de temps a consacrer a open3cl ces temps-ci :(

**Comment by trecouvr** [comment]
Bonjour,

Je rebondi sur ce thread, super boulot !

J'ai aussi la majeur partie des tests qui plantent : 

```
Test Suites: 14 failed, 23 passed, 37 total
Tests:       24658 failed, 1988 skipped, 31686 passed, 58332 total
Snapshots:   0 total
Time:        165.239 s
Ran all test suites.
```

Est-ce que le souci ne vient pas du fait que la lib évolue sensiblement avec la réglementation (ex : exceptions petites surfaces, mise à jour de la table valeur, ...) mais pas le corpus de test ?

J'ai remarqué que enums.js et tv.js n'est pas à jour avec les dernières versions du repo gitlab du gouvernement, mais je suppose que si je sync ça va provoquer encore plus d'erreurs dans les tests ?

J'ai fait quelques modifs/fixs sur la lib, mais je ne suis pas sur de la marche à suivre pour les introduire vu que les tests plantent. Est-ce qu'il y a moyen de lancer uniquement une partir des tests et qui me permettrait d'etre serein sur le fait que je n'ai pas cassé des trucs ?

A+
